// End-to-end API checks on a disposable database. No real messages or production records.
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gestor-check-'));
process.env.DB_PATH=path.join(dir,'test.sqlite');
process.env.BACKUP_DIR=path.join(dir,'backups');
process.env.NOTIFICATIONS_DISABLED='1';process.env.BACKUPS_DISABLED='1';process.env.JWT_SECRET='isolated-test-secret';
const app=require('../server'),db=require('../db');
const server=app.listen(0,'127.0.0.1');
async function main(){
 await new Promise(r=>server.listening?r():server.once('listening',r));
 const base='http://127.0.0.1:'+server.address().port;
 let token;
 async function api(method,url,body,expect=200,auth=token){
 const res=await fetch(base+'/api'+url,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await res.json();assert.equal(res.status,expect,method+' '+url+' '+JSON.stringify(data));return data;
 }
 token=(await api('POST','/auth/login',{email:'admin@empresa.com',password:'admin123'})).token;
 const settings=await api('PUT','/sistema/canales',{empresa:'Empresa de prueba',email_enabled:false,whatsapp_enabled:false,smtp_pass:'test-secret',whatsapp_token:'test-meta-secret'});
 assert.equal(settings.smtp_pass,undefined);assert.equal(settings.smtp_pass_guardado,true);
 assert(!db.prepare("SELECT valor FROM ajustes_app WHERE clave='canales'").get().valor.includes('test-secret'));
 await api('PUT','/sistema/canales',{smtp_pass:''});
 assert.equal(require('../services/canales').leer().smtp_pass,'test-secret');
 const a=await api('POST','/auth/usuarios',{nombre:'Ana',email:'ana@example.test',password:'testpass123',rol:'empleado',horario_fijo:'manana'},201);
 const b=await api('POST','/auth/usuarios',{nombre:'Beto',password:'testpass123'},201);
 await api('PUT','/auth/usuarios/'+a.id,{horario_fijo:null});
 assert.equal(db.prepare('SELECT horario_fijo FROM usuarios WHERE id=?').get(a.id).horario_fijo,null);
 await api('POST','/auth/usuarios',{nombre:'Bad',rol:'superadmin'},400);
 const empleado=(await api('POST','/auth/login',{email:'ana@example.test',password:'testpass123'})).token;
 await api('PUT','/reglas',{min_manana:'1',min_tarde:'1',max_manana:'2',max_tarde:'2'});
 await api('PUT','/reglas',{min_manana:'3',max_manana:'1'},400);
 await api('POST','/descansos',{usuario_id:a.id,fecha:'2030-01-08'},201);
 await api('POST','/turnos',{usuario_id:a.id,fecha:'2030-01-08',tipo:'manana'},409);
 const t=await api('POST','/turnos',{usuario_id:a.id,fecha:'2030-01-07',tipo:'manana'},201);
 await api('POST','/turnos',{usuario_id:a.id,fecha:'2030-01-07',tipo:'tarde'},409);
 await api('POST','/turnos',{usuario_id:a.id,fecha:'2030-02-31',tipo:'tarde'},409);
 await api('POST','/descansos',{usuario_id:a.id,fecha:'2030-01-07'},409);
 await api('POST','/turnos',{usuario_id:a.id,fecha:'2030-01-09',tipo:'manana'},403,empleado);
 const solicitud=await api('POST','/solicitudes',{turno_id:t.id,tipo_nuevo:'tarde',fecha_nueva:'2030-01-07',motivo:'Prueba'},201,empleado);
 await api('POST','/solicitudes',{turno_id:t.id,tipo_nuevo:'tarde',fecha_nueva:'2030-01-07',motivo:'Duplicada'},409,empleado);
 await api('PUT','/solicitudes/'+solicitud.id+'/aprobar',{});
 assert.equal(db.prepare('SELECT tipo FROM turnos WHERE id=?').get(t.id).tipo,'tarde');
 await api('PUT','/solicitudes/'+solicitud.id+'/aprobar',{},409);
 const avisos=await api('GET','/notificaciones',undefined,200,empleado);assert(avisos.length>=2);
 await api('PUT','/notificaciones/leer-todas',{},200,empleado);
 assert.equal((await api('GET','/notificaciones/count',undefined,200,empleado)).count,0);
 const sinEmail=await api('POST','/turnos',{usuario_id:b.id,fecha:'2030-01-09',tipo:'manana'},201);
 assert(db.prepare('SELECT id FROM notificaciones WHERE usuario_id=?').get(b.id));
 const before=db.prepare('SELECT COUNT(*) n FROM turnos').get().n;
 const preview=await api('POST','/turnos/previsualizar',{lunes:'2030-01-07'});
 assert.equal(db.prepare('SELECT COUNT(*) n FROM turnos').get().n,before);
 const generado=await api('POST','/turnos/generar',{lunes:'2030-01-07'});
 assert.equal(generado.creados,preview.creados);
 assert.equal((await api('POST','/turnos/generar',{lunes:'2030-01-07'})).creados,0);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM (SELECT usuario_id,fecha FROM turnos GROUP BY usuario_id,fecha HAVING COUNT(*)>1)').get().n,0);
 assert.equal(db.prepare("SELECT COUNT(*) n FROM turnos WHERE usuario_id=? AND fecha='2030-01-08'").get(a.id).n,0);
 await api('POST','/turnos/generar',{lunes:'2030-01-08'},400);
 for(const reporte of ['cobertura','empleados','areas','solicitudes'])await api('GET','/reportes/'+reporte+'?desde=2030-01-01&hasta=2030-01-31');
 await api('GET','/reportes/cobertura',undefined,403,empleado);
 await api('GET','/sistema/canales',undefined,403,empleado);
 await api('PUT','/auth/usuarios/'+a.id,{activo:0});
 await api('GET','/auth/me',undefined,401,empleado);
 await api('PUT','/auth/usuarios/1',{activo:0},409);
 await api('DELETE','/auth/usuarios/'+a.id);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM descansos WHERE usuario_id=?').get(a.id).n,0);
 await api('DELETE','/turnos/'+sinEmail.id);
 const backup=await api('POST','/sistema/respaldo',{});
 const Database=require('better-sqlite3'),copia=new Database(path.join(process.env.BACKUP_DIR,backup.nombre),{readonly:true});
 assert.equal(copia.pragma('integrity_check',{simple:true}),'ok');copia.close();
 await api('PUT','/auth/cuenta',{password_actual:'wrong',password_nueva:'newpassword'},400);
 await api('PUT','/auth/cuenta',{password_actual:'admin123',password_nueva:'newpassword'});
 await api('GET','/auth/me',undefined,401);
 await api('POST','/auth/login',{email:'admin@empresa.com',password:'newpassword'});
 console.log('PASS full API cycle, generation preview/idempotence, conflicts/rests, roles, notifications, backups and session revocation');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close(()=>{
 db.close();
 const resolved=path.resolve(dir),temp=path.resolve(os.tmpdir())+path.sep;
 if(!resolved.startsWith(temp)||!path.basename(resolved).startsWith('gestor-check-'))throw Error('Unexpected test directory');
 fs.rmSync(resolved,{recursive:true,force:true});
}));
